name: Running for continuous integration
on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - "*"
jobs:
   linters:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Setup nodejs
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: "npm"
         - name: Install dependencies
           run: npm install
         - name: Run linters
           run: npm run lint
   tests:
      runs-on: ubuntu-latest
      needs: [linters]
      steps:
         - uses: actions/checkout@v3
         - name: Setup nodejs
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: "npm"
         - name: Install dependencies
           run: npm install
         - name: Run tests
           run: npm test
